// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "savoysecsii.h"

/////////////////////////////////////////////////////////////////////////////
// CSavoySecsII

IMPLEMENT_DYNCREATE(CSavoySecsII, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSavoySecsII properties

short CSavoySecsII::GetAppearance()
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I2, propVal);
}

short CSavoySecsII::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

long CSavoySecsII::GetBlockNumber()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetBlockNumber(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

CString CSavoySecsII::GetMsg()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetMsg(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

long CSavoySecsII::GetDeviceID()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetDeviceID(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CSavoySecsII::GetEbit()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetEbit(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

short CSavoySecsII::GetFunction()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetFunction(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

CString CSavoySecsII::GetNode()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetNode(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

long CSavoySecsII::GetNodeCount()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetNodeCount(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

short CSavoySecsII::GetNodeType()
{
	short result;
	GetProperty(0x8, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetNodeType(short propVal)
{
	SetProperty(0x8, VT_I2, propVal);
}

CString CSavoySecsII::GetNodeValue()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetNodeValue(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

CString CSavoySecsII::GetNodeValueHex()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetNodeValueHex(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

short CSavoySecsII::GetPType()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetPType(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

BOOL CSavoySecsII::GetRbit()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetRbit(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

short CSavoySecsII::GetSType()
{
	short result;
	GetProperty(0xd, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetSType(short propVal)
{
	SetProperty(0xd, VT_I2, propVal);
}

long CSavoySecsII::GetSessionID()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetSessionID(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

CString CSavoySecsII::GetSml()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetSml(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

long CSavoySecsII::GetSourceID()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetSourceID(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

short CSavoySecsII::GetStream()
{
	short result;
	GetProperty(0x11, VT_I2, (void*)&result);
	return result;
}

void CSavoySecsII::SetStream(short propVal)
{
	SetProperty(0x11, VT_I2, propVal);
}

long CSavoySecsII::GetSystemBytes()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetSystemBytes(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CSavoySecsII::GetTransactionID()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CSavoySecsII::SetTransactionID(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

BOOL CSavoySecsII::GetWbit()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetWbit(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

CString CSavoySecsII::GetXml()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetXml(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

CString CSavoySecsII::GetSuggestedReplyMsg()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CSavoySecsII::SetSuggestedReplyMsg(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

BOOL CSavoySecsII::GetHost()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetHost(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CSavoySecsII::GetHsms()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetHsms(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

BOOL CSavoySecsII::GetErrorDialog()
{
	BOOL result;
	GetProperty(0x19, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetErrorDialog(BOOL propVal)
{
	SetProperty(0x19, VT_BOOL, propVal);
}

BOOL CSavoySecsII::GetAsync()
{
	BOOL result;
	GetProperty(0x1a, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetAsync(BOOL propVal)
{
	SetProperty(0x1a, VT_BOOL, propVal);
}

BOOL CSavoySecsII::GetError()
{
	BOOL result;
	GetProperty(0x1b, VT_BOOL, (void*)&result);
	return result;
}

void CSavoySecsII::SetError(BOOL propVal)
{
	SetProperty(0x1b, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSavoySecsII operations

void CSavoySecsII::Reset()
{
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CSavoySecsII::Reply(LPCTSTR lpszMsgHeader)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 lpszMsgHeader);
}

short CSavoySecsII::Verify()
{
	short result;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CSavoySecsII::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
