// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "savoyhsms.h"

/////////////////////////////////////////////////////////////////////////////
// CSavoyHsms

IMPLEMENT_DYNCREATE(CSavoyHsms, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSavoyHsms properties

short CSavoyHsms::GetAppearance()
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I2, (void*)&result);
	return result;
}

void CSavoyHsms::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I2, propVal);
}

short CSavoyHsms::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
	return result;
}

void CSavoyHsms::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

BOOL CSavoyHsms::GetConnect()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CSavoyHsms::SetConnect(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

CString CSavoyHsms::GetMyHostName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CSavoyHsms::SetMyHostName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CSavoyHsms::GetIPAddress()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CSavoyHsms::SetIPAddress(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CSavoyHsms::GetIniFileName()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CSavoyHsms::SetIniFileName(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CSavoyHsms::GetIniSection()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CSavoyHsms::SetIniSection(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

long CSavoyHsms::GetMyPortNumber()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetMyPortNumber(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CSavoyHsms::GetPortNumber()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetPortNumber(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

BOOL CSavoyHsms::GetSelected()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CSavoyHsms::SetSelected(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CSavoyHsms::GetServer()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CSavoyHsms::SetServer(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

long CSavoyHsms::GetT3()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetT3(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

long CSavoyHsms::GetT5()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetT5(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CSavoyHsms::GetT6()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetT6(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

long CSavoyHsms::GetT7()
{
	long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetT7(long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

long CSavoyHsms::GetT8()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetT8(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

BOOL CSavoyHsms::GetLog()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CSavoyHsms::SetLog(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

short CSavoyHsms::GetLogBakCount()
{
	short result;
	GetProperty(0x10, VT_I2, (void*)&result);
	return result;
}

void CSavoyHsms::SetLogBakCount(short propVal)
{
	SetProperty(0x10, VT_I2, propVal);
}

CString CSavoyHsms::GetLogFileName()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CSavoyHsms::SetLogFileName(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

long CSavoyHsms::GetLogSize()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CSavoyHsms::SetLogSize(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

BOOL CSavoyHsms::GetLogVerbose()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CSavoyHsms::SetLogVerbose(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSavoyHsms operations

CString CSavoyHsms::ToIPAddress(LPCTSTR lpszHostName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lpszHostName);
	return result;
}

BOOL CSavoyHsms::Disconnect(LPCTSTR lpszIPAddress, long lPortNumber)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lpszIPAddress, lPortNumber);
	return result;
}

BOOL CSavoyHsms::Setup(LPCTSTR lpszCaption)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lpszCaption);
	return result;
}

BOOL CSavoyHsms::Send(LPCTSTR lpszMessage)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lpszMessage);
	return result;
}

BOOL CSavoyHsms::LoadIniFile()
{
	BOOL result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CSavoyHsms::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
