#if !defined(AFX_SAVOYHSMS_H__EBC494D4_C52C_4E8A_824A_EDD2C4F97E6F__INCLUDED_)
#define AFX_SAVOYHSMS_H__EBC494D4_C52C_4E8A_824A_EDD2C4F97E6F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSavoyHsms wrapper class

class CSavoyHsms : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSavoyHsms)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6b61ff42, 0x27c9, 0x49e3, { 0xb9, 0xf, 0xcb, 0x64, 0xb6, 0x6, 0x48, 0x80 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetAppearance();
	void SetAppearance(short);
	short GetBorderStyle();
	void SetBorderStyle(short);
	BOOL GetConnect();
	void SetConnect(BOOL);
	CString GetMyHostName();
	void SetMyHostName(LPCTSTR);
	CString GetIPAddress();
	void SetIPAddress(LPCTSTR);
	CString GetIniFileName();
	void SetIniFileName(LPCTSTR);
	CString GetIniSection();
	void SetIniSection(LPCTSTR);
	long GetMyPortNumber();
	void SetMyPortNumber(long);
	long GetPortNumber();
	void SetPortNumber(long);
	BOOL GetSelected();
	void SetSelected(BOOL);
	BOOL GetServer();
	void SetServer(BOOL);
	long GetT3();
	void SetT3(long);
	long GetT5();
	void SetT5(long);
	long GetT6();
	void SetT6(long);
	long GetT7();
	void SetT7(long);
	long GetT8();
	void SetT8(long);
	BOOL GetLog();
	void SetLog(BOOL);
	short GetLogBakCount();
	void SetLogBakCount(short);
	CString GetLogFileName();
	void SetLogFileName(LPCTSTR);
	long GetLogSize();
	void SetLogSize(long);
	BOOL GetLogVerbose();
	void SetLogVerbose(BOOL);

// Operations
public:
	CString ToIPAddress(LPCTSTR lpszHostName);
	BOOL Disconnect(LPCTSTR lpszIPAddress, long lPortNumber);
	BOOL Setup(LPCTSTR lpszCaption);
	BOOL Send(LPCTSTR lpszMessage);
	BOOL LoadIniFile();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SAVOYHSMS_H__EBC494D4_C52C_4E8A_824A_EDD2C4F97E6F__INCLUDED_)
