#if !defined(AFX_SAVOYSECSII_H__3EC4C0C6_2C3C_4A0D_9D7F_E2B06C80FA34__INCLUDED_)
#define AFX_SAVOYSECSII_H__3EC4C0C6_2C3C_4A0D_9D7F_E2B06C80FA34__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSavoySecsII wrapper class

class CSavoySecsII : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSavoySecsII)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x351b5374, 0x7f93, 0x4dd7, { 0x96, 0xc1, 0x65, 0x5a, 0x10, 0xf, 0xc, 0xbe } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetAppearance();
	void SetAppearance(short);
	short GetBorderStyle();
	void SetBorderStyle(short);
	long GetBlockNumber();
	void SetBlockNumber(long);
	CString GetMsg();
	void SetMsg(LPCTSTR);
	long GetDeviceID();
	void SetDeviceID(long);
	BOOL GetEbit();
	void SetEbit(BOOL);
	short GetFunction();
	void SetFunction(short);
	CString GetNode();
	void SetNode(LPCTSTR);
	long GetNodeCount();
	void SetNodeCount(long);
	short GetNodeType();
	void SetNodeType(short);
	CString GetNodeValue();
	void SetNodeValue(LPCTSTR);
	CString GetNodeValueHex();
	void SetNodeValueHex(LPCTSTR);
	short GetPType();
	void SetPType(short);
	BOOL GetRbit();
	void SetRbit(BOOL);
	short GetSType();
	void SetSType(short);
	long GetSessionID();
	void SetSessionID(long);
	CString GetSml();
	void SetSml(LPCTSTR);
	long GetSourceID();
	void SetSourceID(long);
	short GetStream();
	void SetStream(short);
	long GetSystemBytes();
	void SetSystemBytes(long);
	long GetTransactionID();
	void SetTransactionID(long);
	BOOL GetWbit();
	void SetWbit(BOOL);
	CString GetXml();
	void SetXml(LPCTSTR);
	CString GetSuggestedReplyMsg();
	void SetSuggestedReplyMsg(LPCTSTR);
	BOOL GetHost();
	void SetHost(BOOL);
	BOOL GetHsms();
	void SetHsms(BOOL);
	BOOL GetErrorDialog();
	void SetErrorDialog(BOOL);
	BOOL GetAsync();
	void SetAsync(BOOL);
	BOOL GetError();
	void SetError(BOOL);

// Operations
public:
	void Reset();
	void Reply(LPCTSTR lpszMsgHeader);
	short Verify();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SAVOYSECSII_H__3EC4C0C6_2C3C_4A0D_9D7F_E2B06C80FA34__INCLUDED_)
